import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import FabButton from "../components/FabButton";
import UrlList from "../components/UrlList";
import styles from "../styles/Home.module.css";
import Link from "../components/Link";
import { userService } from "../services/user.service";

export default function Home() {
  const sendDataToReactNativeApp = async () => {
    window.ReactNativeWebView.postMessage(
      "Hello from Webview to React Native 🙋‍♂️"
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="w-full text-center text-3xl text-black p-4 rounded-md my-8">
          Search your Videos
        </div>
        <UrlList />
      </main>
      <Link href="/add">
        <div className={styles.fabContainer}>
          <FabButton />
        </div>
      </Link>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// export default function Home() {
//   return (
//     <div className="p-4">
//       <div className="container">
//         <h1>Hi {userService.userValue?.firstName}!</h1>
//         <p>You&apos;re logged in with Next.js & JWT!!</p>
//         <p>
//           <Link href="/users">Manage Users</Link>
//         </p>
//       </div>
//     </div>
//   );
// }
